name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Release branch to deploy'
        required: true

jobs:
  deploy_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0  # Fetch full history

      - name: Deploy to staging
        run: |
          echo "✅ Deploying branch ${{ inputs.branch }} to staging..."

      - name: Tag the branch as staging
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.event.inputs.branch }}
          REPOSITORY: ${{ github.repository }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}

          # Moving staging tag
          git tag -f staging
          git push origin -f staging

          VERSION="$BRANCH"
          VERSION="${VERSION#release/}"
          TIMESTAMP=$(date -u +'%Y%m%d-%H%M')

          HIST_TAG="staging-${VERSION}-${TIMESTAMP}"
          git tag "$HIST_TAG"
          git push origin "$HIST_TAG"

          echo "✅ Updated tags: staging and $HIST_TAG"
