name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Release branch to deploy'
        required: true

jobs:
  deploy_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Deploy to staging
        run: |
          echo "✅ Deploying branch ${{ inputs.branch }} to staging..."
          # Add your real deployment logic here (e.g., SSH, docker build, kubectl, etc)
