name: Tag and Release on Merge

on:
  push:
    branches:
      - master

jobs:
  tag_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Needed to get the previous commit
          
      - name: Extract version from branch name
        if: contains(env.SOURCE_BRANCH, 'release/')
        run: |
          VERSION="${{ github.event.pull_request.head.ref#release/ }}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Tagging with version v$VERSION"

      - name: Create and push tag
        if: env.VERSION != ''
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "v${VERSION}"
          git push origin "v${VERSION}"
