name: Tag and Release on Merge

on:
  push:
    branches:
      - master

jobs:
  tag_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get previous commit message
        id: commit
        run: |
          echo "COMMIT_MSG=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Check if commit is from release/*
        if: contains(env.COMMIT_MSG, 'release/')
        run: |
          echo "Detected merge from release branch."

      - name: Extract version from commit message
        if: contains(env.COMMIT_MSG, 'release/')
        id: extract
        run: |
          VERSION=$(echo "$COMMIT_MSG" | grep -oE 'release/[0-9]+\.[0-9]+\.[0-9]+' | head -n 1 | cut -d/ -f2)
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create and push tag
        if: env.VERSION != ''
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "v${VERSION}"
          git push origin "v${VERSION}"
