name: Tag and Release on Merge

on:
  push:
    branches:
      - master

jobs:
  tag-release:
    if: github.event.pull_request.head.ref startsWith 'release/'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from branch
        id: version
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION="${BRANCH_NAME##release/}"
          echo "VERSION=v$VERSION" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $VERSION
          git push origin $VERSION
