name: Tag and Release on Merge

on:
  push:
    branches:
      - master

jobs:
  tag_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from branch name
        run: |
          # Get branch ref like refs/heads/release/1.1.1
          REF_NAME="${GITHUB_REF#refs/heads/}"
          echo "Full ref: $REF_NAME"

          # Remove release/ prefix
          VERSION="${REF_NAME#release/}"
          echo "Extracted version: $VERSION"

          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "v$VERSION"
          git push origin "v$VERSION"
