name: Validate Migration Naming

on: [pull_request]

jobs:
  check-migration-naming:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
         fetch-depth: 0  # Fetch all history to ensure full history is available

      - name: Check Migration File Naming
        run: |
          # Regex pattern for Visual Studio migration timestamp format
          MIGRATION_PATTERN="^[0-9]{14}_[A-Za-z0-9]+\.cs$"
          
          # Get list of added/modified migration files
          INVALID_FILES=$(git diff --name-only origin/main | grep "Migrations/.*\.cs" | grep -vE "$MIGRATION_PATTERN" || true)

          if [[ -n "$INVALID_FILES" ]]; then
              echo "❌ ERROR: The following migration files do not follow naming conventions:"
              echo "$INVALID_FILES"
              echo "✅ Use format: YYYYMMDDHHMMSS_Action_Entity.cs (e.g., 20250317093601_CreateUsersTable.cs)"
              exit 1
          fi

          echo "✅ Migration file naming check passed."
